name: Trigger E2E tests

on: pull_request
#  pull_request:
#    types:
#      - labeled

jobs:
  tigger-e2e:
#    if: github.event.label.name == 'approved'
    name: Trigger E2E tests workflow on CircleCI
    runs-on: ubuntu-latest
    steps:
    - name: Trigger E2E tests workflow on CircleCI
      run: >
        curl --request POST
        --url https://circleci.com/api/v2/project/gh/storybookjs/storybook/pipeline
        --header 'Circle-Token: '"$CIRCLE_CI_TOKEN"' '
        --header 'content-type: application/json'
        --data '{"branch":"${{ github.event.pull_request.head.ref }}", "parameters":{"run_workflow_deploy":false, "run_workflow_e2e":true, "run_workflow_test":false}}'
      env:
        CIRCLE_CI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN_GMAISSE_TEST }}
